apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- kustomization-rancher.yaml
- kustomization-cert-manager.yaml
- kustomization-home-assistant.yaml
- kustomization-n8n.yaml
