apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: airflow
  namespace: flux-system
spec:
  interval: 1m
  path: "clusters/schuk/apps/airflow"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
