# clusters/schuk/flux-system/rancher-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rancher
  namespace: flux-system
spec:
  interval: 1m
  path: "../infrastructure/rancher"   # Pfad relativ zu flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
